# Generated by Django 5.1.1 on 2024-09-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_book_description_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='Description', max_length=1000),
        ),
    ]
