# Generated by Django 5.1.1 on 2024-09-06 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_alter_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('book_reading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims_app.book')),
            ],
        ),
    ]
