# Generated by Django 5.1.1 on 2024-09-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
